default_stages: [commit]
repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: clippy
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.9.0
    hooks:
      - id: eslint
        files: \.[jt]s$
        types: [file]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
